name: builds on Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ next ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.cfg.os }}

    strategy:
        matrix:
            cfg:
              - descr: Ogon native Ubuntu-22.04
                os: Ubuntu-22.04
                file: forgiare.accendino
                targets: forgiare
              - descr: Ogon native Ubuntu-24.04
                os: Ubuntu-24.04
                file: forgiare.accendino
                targets: forgiare
              - descr: FreeRDP clang build on Ubuntu-24.04
                os: Ubuntu-24.04
                file: freerdp.accendino
                targets: freerdp3
                extraArgs: --toolchain=clang
                isClang: yes
              - descr: Mingw64 cross build of FreeRDP
                os: Ubuntu-24.04
                file: freerdp.accendino
                targets: freerdp3
                extraArgs: --targetDistrib=mingw64
                isMingw: yes
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: update package index
        run: sudo apt update

      - name: cross compile packages
        if: ${{ matrix.cfg.isMingw == 'yes'}}
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64

      - name: install clang
        if: ${{ matrix.cfg.isClang == 'yes'}}
        run: sudo apt install clang

      - name: Install ${{ matrix.cfg.descr }}
        run: python3 -m pip install .

      - name: Test ${{ matrix.cfg.descr }}
        run: accendino --prefix=/tmp/ogon --targets=${{ matrix.cfg.targets }} ${{ matrix.cfg.extraArgs }} --debug ${{ matrix.cfg.file }}

